# words for hangman game

words = ("aardvark","alligator","antelope","bear","beaver","buffalo","camel","cat","cheetah","chimpanzee",
    "cow","coyote","crab","deer","dog","dolphin","donkey","duck","eagle","ferret","fish","fox",
    "frog","goat","goose","gorilla","hamster","hawk","horse","hyena","jellyfish","kangaroo","koala",
    "lemur","leopard","lion","lizard","lobster","moose","mouse","octopus","otter","owl","ox","panda",
    "parrot","peacock","penguin","pig","porcupine","rabbit","raccoon","rat","seal","shark","sheep",
    "skunk","sloth","snake","sparrow","spider","squid","swan","tiger","turkey","turtle","walrus",
    "weasel","whale","wolf","wombat","yak","zebra","apple","apricot","avocado","banana","blueberry","bread","broccoli","butter","cabbage","cake",
    "carrot","celery","cheese","cherry","chocolate","coconut","coffee","cookie","corn","cranberry",
    "cucumber","donut","egg","fig","garlic","grape","honey","icecream","kiwi","lemon","lettuce",
    "lime","mango","melon","milk","mushroom","nut","oatmeal","olive","onion","orange","papaya",
    "peach","pear","pepper","pineapple","plum","potato","pumpkin","radish","raspberry","rice",
    "salad","salt","sandwich","spinach","strawberry","sugar","tea","tomato","walnut","watermelon",
    "yogurt","zucchini","airport","bank","beach","bridge","canyon","castle","church","city","cliff","desert","farm",
    "forest","garden","harbor","hospital","hotel","house","island","lake","library","market",
    "mountain","museum","ocean","park","palace","plaza","port","river","school","stadium","station",
    "street","temple","tower","town","university","valley","village","volcano","waterfall","zoo","accept","add","admire","agree","allow","answer","arrive","ask","bake","begin","believe","build",
    "buy","call","carry","catch","choose","climb","close","collect","cook","create","dance","decide",
    "deliver","discover","draw","drink","drive","eat","enjoy","explore","fall","feed","fight","find",
    "fly","follow","forget","forgive","give","grow","help","hope","imagine","improve","jump","keep",
    "know","laugh","learn","listen","live","look","love","make","move","open","paint","play","read",
    "remember","run","say","see","sell","send","sing","sit","sleep","smile","speak","stand","study",
    "swim","take","teach","think","travel","try","understand","use","visit","wait","walk","watch",
    "win","work","write","angry","beautiful","big","bitter","brave","bright","busy","calm","careful","cheap","clean",
    "cold","colorful","cool","crazy","cute","dark","deep","delicious","dry","early","easy","empty",
    "fast","fat","friendly","funny","gentle","good","great","happy","hard","heavy","hot","hungry",
    "kind","lazy","light","little","long","loud","lovely","modern","new","nice","old","poor","pretty",
    "quick","quiet","rich","sad","safe","short","slow","small","soft","strong","sweet","tall","thin",
    "tired","ugly","warm","weak","wet","wild","wise","young", "algorithm","array","binary","bit","byte","cache","class","cloud","compile","computer","data",
    "database","debug","device","digital","electric","engine","file","function","genome","hardware",
    "internet","java","logic","machine","matrix","memory","model","network","node","object","pixel",
    "program","python","robot","science","server","software","string","system","technology","variable",
    "vector","virtual")